# Generated by Django 3.1.1 on 2020-09-17 23:00

import cmdb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cmdb.models.StringField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Asset kind',
                'verbose_name_plural': 'Assets kind',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', cmdb.models.StringField(choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], default='Virtual', max_length=250, verbose_name='Kind')),
                ('name', cmdb.models.StringField(max_length=250, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('serial', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Service tag or serial')),
                ('license', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Key or license')),
                ('patrimony', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Patrimony ID')),
                ('purpose', cmdb.models.StringField(max_length=250, verbose_name='Purpose')),
                ('cpu', models.PositiveIntegerField(verbose_name='CPU')),
                ('ram', models.PositiveIntegerField(verbose_name='RAM in GB')),
                ('last_operation_system_upgrade', models.DateField(blank=True, null=True, verbose_name='Last operation system upgrade')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cmdb.models.StringField(max_length=250, verbose_name='Name')),
                ('end_of_life', models.DateField(blank=True, null=True, verbose_name='End of life')),
            ],
            options={
                'verbose_name': 'Operation system',
                'verbose_name_plural': 'Operation systems',
            },
        ),
        migrations.CreateModel(
            name='OperationSystemFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cmdb.models.StringField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Operation system family',
                'verbose_name_plural': 'Operation system families',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cmdb.models.StringField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', cmdb.models.StringField(choices=[('SSD', 'SSD'), ('HD', 'HD'), ('VHD', 'VHD')], default='VHD', max_length=250, verbose_name='Kind')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity (in GB)')),
                ('machine', cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
        migrations.CreateModel(
            name='OperationSystemVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', cmdb.models.StringField(max_length=250, verbose_name='Name')),
                ('operation_system', cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.operationsystem', verbose_name='Operation system')),
            ],
            options={
                'verbose_name': 'Operation system version',
                'verbose_name_plural': 'Operation system versions',
            },
        ),
        migrations.AddField(
            model_name='operationsystem',
            name='family',
            field=cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.operationsystemfamily', verbose_name='Family'),
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Purpose')),
                ('interface_name', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Interface name')),
                ('interface_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Interface number')),
                ('ipv4_address', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='IPv4 address')),
                ('ipv4_mask', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='IPv4 mask')),
                ('ipv6_address', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='IPv6 address')),
                ('switch_port', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Switch port')),
                ('pvid', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='PVID')),
                ('untag', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Untag')),
                ('tag', cmdb.models.NullStringField(blank=True, max_length=250, null=True, verbose_name='Tag')),
                ('machine', cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.machine', verbose_name='Machine')),
                ('service', cmdb.models.NullFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Network interface',
                'verbose_name_plural': 'Network interfaces',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='operation_system_version',
            field=cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.operationsystemversion', verbose_name='Operation system version'),
        ),
        migrations.AddField(
            model_name='machine',
            name='physical_machine',
            field=cmdb.models.NullFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.machine', verbose_name='Physical machine'),
        ),
        migrations.CreateModel(
            name='ExecutedCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commands', models.TextField(verbose_name='Commands')),
                ('date', models.DateField(verbose_name='Date')),
                ('machine', cmdb.models.NullFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Executed commands',
                'verbose_name_plural': 'Executed commands',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', cmdb.models.StringField(choices=[('Local', 'Local'), ('Service', 'Service'), ('LDAP', 'LDAP')], default='Local', max_length=250, verbose_name='Kind')),
                ('username', cmdb.models.StringField(max_length=250, verbose_name='Username')),
                ('password', cmdb.models.StringField(max_length=250, verbose_name='Password')),
                ('machine', cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='ConfiguredAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('asset', cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.assetkind', verbose_name='Asset')),
                ('machine', cmdb.models.FK(on_delete=django.db.models.deletion.CASCADE, to='cmdb.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Configured asset',
                'verbose_name_plural': 'Configured assets',
            },
        ),
    ]
